name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build 🔧
        id: install-deps
        run: pnpm run build

      - name: Publish package on NPM 📦
        id: npm-publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}